# Generated by Django 3.0.2 on 2020-01-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200112_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_picture',
            field=models.CharField(blank=True, default='https://images-na.ssl-images-amazon.com/images/I/617LYNQsELL.jpg', max_length=500),
        ),
    ]
